-- Permisos para usuario_admin
INSERT INTO permiso (codigo, descripcion) VALUES
('G_CLIENTE', 'GESTIONAR CLIENTE'),
('G_CLIENTE_CUENTA', 'GESTIONAR CUENTA DEL CLIENTE'),
('G_ROL', 'GESTIONAR ROL'),
('G_USUARIOS_ADMIN', 'GESTIONAR USUARIOS ADMINISTRATIVOS'),
('G_FACTURA_GENERAR', 'GENERAR FACTURAS'),
('G_PAGO_REGISTRAR', 'RESGISTRAR PAGOS'),
('G_GASTO_REGISTRAR', 'RESGISTRAR GASTOS'),
('G_LECTURA', 'REGISTRAR LECTURAS');

-- Permisos para cuenta_cliente
INSERT INTO permiso (codigo, descripcion) VALUES 
('G_PAGO', 'REALIZAR PAGOS DE FACTURAS'),
('V_GASTOS', 'VISUALIZAR GASTOS');
